package database_maks_pkg;

import java.io.File;
import java.sql.SQLException;

/** Abstract class for files.
 *
 * Convenience class. Essentially a way to store common code for TruthFiles and SensorDataFiles.
 *
 */
public abstract class Files extends Table {


    /** Getter for just Filename
     *
     * Note that filename in MATLAB layer is name in java layer.
     *
     * @param uid file UID
     * @return filename without extension
     * @throws SQLException
     */
    public String getFilename(int uid) throws SQLException {
        String query = "SELECT "+tableName+".name FROM " + tableName + " WHERE uid = " + uid;
        return getStringAttrib(query, "name");
    }

    /** Getter for Path
     *
     * Conversion doesn't need to be performed: http://stackoverflow.com/a/1697362
     * but just in case it's still being done.
     *
     * @param uid file UID
     * @return path to file
     * @throws SQLException
     */
    public String getPath(int uid) throws SQLException {
        String query = "SELECT "+tableName+".path FROM " + tableName + " WHERE uid = " + uid;
        return getStringAttrib(query, "path").replace("/",File.separator);
    }

    /** Getter fir MD5 of file.
     *
     * These are not generated by this database_maks_pkg (yet) but a relic of Ken's. Mostly deprecated as far as I can tell.
     *
     * @param uid file UID
     * @return MD5 string.
     * @throws SQLException
     */
    public String getMD5(int uid) throws SQLException {
        String query = "SELECT "+tableName+".md5 FROM " + tableName + " WHERE uid = " + uid;
        return getStringAttrib(query, "md5");
    }



}

